### ISSUE TITLE
테스트 페이지 존재 및 파이어베이스 스토리지 권한 변경

### ISSUE THREAD

**Issue by Gumball12** [LikeLionSCH/HACKYOURLIFE_SCH#231]
안녕하세요.

다름이 아니라 테스트 페이지가 남아있으며,
이를 이용해 임의로 사진 파일을 업로드 할 수 있기에 삭제하는 것이 좋을 것 같습니다.

- [/main/urls.py](https://github.com/LikeLionSCH/HACKYOURLIFE_SCH/blob/main/main/urls.py#L7)
- [/main/views.py](https://github.com/LikeLionSCH/HACKYOURLIFE_SCH/blob/main/main/views.py#L80)
- [/main/templates/test.html](https://github.com/LikeLionSCH/HACKYOURLIFE_SCH/blob/main/main/templates/test.html)

추가적으로 파이어베이스 스토리지 권한이 설정되어 있지 않은 것 같아요.

다음의 코드로 현재 [Notice 페이지에 올라온 글](https://schlikelion.org/notice/detail/ft0XUa9LkHZ5QFymYRgh) 이미지를 임의로 조작할 수 있습니다.

```js
// in chrome dev tool console

// delete 'Notice/slogan2.png' image
firebase.storage().ref('Notice/slogan2.png').delete();

// put other 'Notice/slogan2.png' image
firebase.storage().ref('Notice/slogan2.png').put(/* file data */);
```

홈페이지 멋져요. 화이팅하세요.

**Comment by HwangSB** [comment]
상세하게 이슈를 등록해주셔서 진심으로 감사드립니다!
덕분에 해당 문제를 수정하는데 큰 도움이 되었습니다. 😄

**Comment by minsgy** [comment]
미키마우스 사진 바꾸신게 이거였군요 👍
